export const SET_DATA_CARE_PATHWAY = "SET_DATA_CARE_PATHWAY";
export const SET_ACTIVE_CHAPTER_CARE_PATHWAY = "SET_ACTIVE_CHAPTER_CARE_PATHWAY";
export const SET_AGE_RANGE_CARE_PATHWAY = "SET_AGE_RANGE_CARE_PATHWAY";
export const SET_AGE_RANGE_DROPDOWN_OPEN_CARE_PATHWAY = "SET_AGE_RANGE_DROPDOWN_OPEN_CARE_PATHWAY";
